### ISSUE TITLE
Consider inclusion of libpipewire

### ISSUE THREAD

**Issue by aiddya** [snapcore/core-base#142]
Screensharing on Wayland requires libpipewire and soon it's going to be necessary for camera access too. However, libpipewire is not available in core22 or the gnome extension. Consider including libpipewire in core22 or the gnome extension so that every application that requires screensharing or camera access does not have to add it to their build recipes.

**Comment by Meulengracht** [comment]
Libpipewire is more appropriate to be included in one of the gnome snaps - we won't be adding it to the base snap.

**Comment by Meulengracht** [comment]
Link for reference: https://github.com/ubuntu/gnome-sdk
