### ISSUE TITLE
Timezone info is not being saved in /etc/**/timezone in uc24

### ISSUE THREAD

**Issue by sergiocazzolato** [snapcore/core-base#197]
Hi, I see the timezone file does not contain the expected value in uc24. This happens when I set timezone with command `snap set system`

Steps: 

google:ubuntu-core-24-64 .../tests/core/snap-set-core-config# snap set system system.timezone=Europe/Malta

google:ubuntu-core-24-64 .../tests/core/snap-set-core-config# snap get system system.timezone
Europe/Malta

google:ubuntu-core-24-64 .../tests/core/snap-set-core-config# cat /etc/timezone 
Etc/UTC

google:ubuntu-core-24-64 .../tests/core/snap-set-core-config# ls -al /etc/timezone 
lrwxrwxrwx 1 root root 17 Mar 18 13:04 /etc/timezone -> writable/timezone

google:ubuntu-core-24-64 .../tests/core/snap-set-core-config# cat /etc/writable/timezone
Etc/UTC

google:ubuntu-core-24-64 .../tests/core/snap-set-core-config# cat /run/mnt/data/system-data/etc/writable/timezone
Etc/UTC

google:ubuntu-core-24-64 .../tests/core/snap-set-core-config# cat /writable/system-data/etc/writable/timezone
Etc/UTC

**Comment by valentindavid** [comment]
What still uses `/etc/timezone`?

I suppose `/etc/localtime` is working correctly, right?

**Comment by valentindavid** [comment]
tzdata package still seems to set that file. But systemd package does not support it anymore. And the commit message for systemd says that it will be removed from tzdata. We should report that to tzdata package.

**Comment by valentindavid** [comment]
https://git.launchpad.net/ubuntu/+source/systemd/commit/?h=ubuntu/noble&id=28efd34bc095a7bae923f13e23198610b5fe253d
