### ISSUE TITLE
MOTD says Ubuntu Core 20

### ISSUE THREAD

**Issue by xnox** [snapcore/core-base#24]
https://github.com/snapcore/core-base/blob/main/hooks/014-set-motd.chroot#L8

Says that this is Ubuntu Core 20 system, it should be updated as appropriate.

**Comment by alfonsosanchezbeato** [comment]
Should be fixed by https://github.com/snapcore/core-base/pull/27

**Comment by mhalano** [comment]
@xnox Can you validate if the fix #27 closes your issue?
