### ISSUE TITLE
There are no dailies for jammy

### ISSUE THREAD

**Issue by alfonsosanchezbeato** [snapcore/core-base#46]
In the past, we downloaded the base from `http://cdimage.ubuntu.com/ubuntu-base/$(LTS)/daily/current/$(BASE)`, and I see that in `http://cdimage.ubuntu.com/ubuntu-base/` there are `bionic` and `focal` subdirectories, but no `jammy` one. So https://github.com/snapcore/core-base/pull/44 changes things to start downloading the base from `http://cdimage.ubuntu.com/ubuntu-base/releases/$(LTS)/release/$(BASE)`, which is available for `jammy`.  The problem is that the base in the releases folder is not updated, and although we do update/upgrade in the hooks, it is not ideal and it would be better to download the latest daily base.

Therefore, I'm opening this issue to remind us to change to daily base builds when those are available for `jammy`.

**Comment by Meulengracht** [comment]
Can this be closed?

**Comment by alfonsosanchezbeato** [comment]
Yup!
