### ISSUE TITLE
Core22 incompatible with Centos

### ISSUE THREAD

**Issue by merlijn-sebrechts** [snapcore/core-base#92]
After switching `signal-desktop` to `core22` with the gnome extension, the snap started to crash on Centos.

https://github.com/snapcrafters/signal-desktop/issues/76

This seems to be caused by the snap using the clone3() syscall, which is not supported by the kernel of Centos.

> The clone3() system call first appeared in Linux 5.3

Is it possible core22 is compiled with a GLIBC that requires Linux 5.3+?

**Comment by Meulengracht** [comment]
That sounds very plausible, AFAICT a clone3 wrapper was introduced in glibc 2.34 (2021-07-14), which tries to call clone3, however should the clone3 system call not be available, it will fall-back to clone2 or clone. So at the same time it would seem to me like it should not crash the snap, unless something else relies on clone3 to be available. And I am fairly certain core22 uses glibc 2.35. (Maybe someone can correct me)

Source for the clone wrapper [here](https://sourceware.org/git/?p=glibc.git;a=blob;f=include/clone_internal.h;hb=f94f6d8a3572840d3ba42ab9ace3ea522c99c0c2)

**Comment by Meulengracht** [comment]
I've investigated this and the root cause is listed here: https://github.com/snapcrafters/signal-desktop/issues/76
